import React from "react";
import Home from "./Home";
import Head from "next/head";
import Header from "./Components/Header/Header";

function HomePage() {
  return (
    <>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /></Head>
    <Header  />

      <Home />
    </>
  );
}

export default HomePage;
